spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: ms-client-route
            uri: http://ms-client
            predicates:
            - Path=/client/**
            filters:
            - AddResponseHeader=X-API, Amigo-Programador-Gateway
          - id: ms-debitcard-route
            uri: http://ms-debitcard
            predicates:
            - Path=/debitcard/**
            filters:
            - AddResponseHeader=X-API, Amigo-Programador-Gateway
          - id: ms-transaction-route
            uri: http://ms-transaction
            predicates:
            - Path=/transaction/**
            filters:
            - AddResponseHeader=X-API, Amigo-Programador-Gateway-
server:
  port: 9999