spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      server:
        webflux:
          routes:
            - id: ms-client-route
              uri: http://localhost:8081
              predicates:
                - Path=/client/**
              filters:
                - RewritePath=/client/(?<segment>.*), /client/${segment}
                - AddRequestHeader=X-Request-Example, Gateway-Request
                - AddResponseHeader=X-Response-Example, Gateway-Response
            - id: ms-debitcard-route
              uri: http://localhost:8082
              predicates:
                - Path=/example/**
              filters:
                - RewritePath=/example/(?<segment>.*), /debitcard/${segment}
                - AddRequestHeader=X-Request-Example, Gateway-Request
                - AddResponseHeader=X-Response-Example, Gateway-Response                
server:
  port: 9999