spring:
  application:
    name: ms-client
  data:
    mongodb:
      database: msclient
      port: '27017'
      host: amigoprogramador-mongodb
  jackson:
    default-property-inclusion: NON_NULL
management:
  endpoint:
    health:
      probes.enabled: true
server:
  port: 8081