spring:
  application:
    name: ms-debitcard
    consume:
      msclient:
        url: http://ms-client/client
  data:
    mongodb:
      database: msdebitcard
      port: '27017'
      host: amigo-programador-mongodb
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  port: '8082'