application:
  consume:
    msclient:
      url: http://msclient:8080/client
spring:
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  application:
    name: ms-debitcard
  data:
    mongodb:
      database: msdebitcard
      port: '27017'
      host: mongodb-dockercompose
server:
  port: '8082'