spring:
  application:
    name: ms-transaction
    consume:
      msdebitcard:
        url: http://ms-debitcard:8082/debitcard
  data:
    mongodb:
      database: mstransaction
      host: mongodb
      port: '27017'
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: '8083'
