application:
  consume:
    msdebitcard:
      url: http://msdebitcard:8082/debitcard
spring:
  application:
    name: ms-transaction
  data:
    mongodb:
      database: mstransaction
      port: '27017'
      host: mongodb-container
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: '8083'
